package com.gatech.cs6400.jsf.dao;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;

import com.gatech.cs6400.jsf.util.DataConnect;
import com.gatech.cs6400.jsf.util.SessionUtils;

public class IncidentDAO {

    public static int insertResource(    String description,
                                         Date date,
                                         String latitude,
                                         String longitude) {
        Connection con = null;
        //Converts from java Date to sql Date
        java.sql.Date sqlDate = new java.sql.Date(date.getTime());
        try {
            con = DataConnect.getConnection();
            PreparedStatement preparedStatement =
                    con.prepareStatement("INSERT INTO incident (Username, Description, Date, Latitude, Longitude) VALUES (?,?,?,?,?)",
                            Statement.RETURN_GENERATED_KEYS);
            // Retrieves username from Session
            preparedStatement.setString(1,SessionUtils.getUserName());
            preparedStatement.setString(2,description);
            preparedStatement.setDate(3,sqlDate);
            preparedStatement.setString(4,latitude);
            preparedStatement.setString(5,longitude);
            preparedStatement.executeUpdate();
            ResultSet tableKeys = preparedStatement.getGeneratedKeys();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            return autoGeneratedID;

        } catch (SQLException ex) {
            System.out.println("Login error -->" + ex.getMessage());
            return -1;
        } finally {
            DataConnect.close(con);
        }
    }
}